
print("comments are fun")
# COMMENT A LINE WHICH WILL NOT BE RENDERRED BY PYTHON. PYTHON JUST IGNORES IT.
# HELPS US WRITE A PLAIN CONTEXT . YOU CAN WRITE COMMENTS BY USING "#"
# EG: THIS PROGRAM IS COOL
# THE ABOVE PRINT STATEMENT PRINTS OUT A STRING
# HOW DO YOU WRITE LONG COMMENTS YOU CAN'T KEEP USING # FOR EVERY LINE.


